export enum LastKnowMessurementsTypes {
  FETCH_LAST_KNOW_MESSUREMENTS_REQUEST = 'FETCH_LAST_KNOW_MESSUREMENTS_REQUEST',
  FETCH_LAST_KNOW_MESSUREMENTS_SUCCESS = 'FETCH_LAST_KNOW_MESSUREMENTS_SUCCESS',
  FETCH_LAST_KNOW_MESSUREMENTS_FAILURE = 'FETCH_LAST_KNOW_MESSUREMENTS_FAILURE',
}
